// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhghxs1DNvRgTLg3DQyTdS8csxT5qzGos',
    appId: '1:901330524655:web:25328ea13166e8a44fbe1a',
    messagingSenderId: '901330524655',
    projectId: 'social-connect-af6d2',
    authDomain: 'social-connect-af6d2.firebaseapp.com',
    storageBucket: 'social-connect-af6d2.firebasestorage.app',
    measurementId: 'G-WF70Q36DS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCrMQKOcSR6otQswcX4_Ok3z4_BgsjROA',
    appId: '1:901330524655:android:5cf12fffbbea40ff4fbe1a',
    messagingSenderId: '901330524655',
    projectId: 'social-connect-af6d2',
    storageBucket: 'social-connect-af6d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpT8nBrXdxqQcN-X1L_63KRzX6GThHRkc',
    appId: '1:901330524655:ios:5471615483b0577c4fbe1a',
    messagingSenderId: '901330524655',
    projectId: 'social-connect-af6d2',
    storageBucket: 'social-connect-af6d2.firebasestorage.app',
    iosBundleId: 'com.sajeel.socialconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpT8nBrXdxqQcN-X1L_63KRzX6GThHRkc',
    appId: '1:901330524655:ios:85830c33702732e44fbe1a',
    messagingSenderId: '901330524655',
    projectId: 'social-connect-af6d2',
    storageBucket: 'social-connect-af6d2.firebasestorage.app',
    iosBundleId: 'com.example.socialConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhghxs1DNvRgTLg3DQyTdS8csxT5qzGos',
    appId: '1:901330524655:web:9233ea9184bc146c4fbe1a',
    messagingSenderId: '901330524655',
    projectId: 'social-connect-af6d2',
    authDomain: 'social-connect-af6d2.firebaseapp.com',
    storageBucket: 'social-connect-af6d2.firebasestorage.app',
    measurementId: 'G-KGYXPP8BVC',
  );
}
